# Generated by Django 5.2.3 on 2025-06-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='carid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
