# Generated by Django 5.2.3 on 2025-06-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bookmark_carid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
