# Generated by Django 5.2.3 on 2025-07-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_car_grade_car_imgname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='plan',
            field=models.JSONField(default=list),
        ),
    ]
