# Generated by Django 5.2.3 on 2025-07-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_color_grade_interior_interiorexteriorupgrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_hex',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='color',
            name='subname',
            field=models.CharField(default='標準色', max_length=100),
        ),
        migrations.AddField(
            model_name='grade',
            name='gasType',
            field=models.CharField(default='ガソリン', max_length=100),
        ),
        migrations.AddField(
            model_name='grade',
            name='wheelDrive',
            field=models.CharField(default='2WD', max_length=100),
        ),
        migrations.AddField(
            model_name='interior',
            name='imgname',
            field=models.CharField(default='default_interior.png', max_length=100),
        ),
    ]
