# Generated by Django 5.2.3 on 2025-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_color_color_hex_color_subname_grade_gastype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interior',
            name='interiorcolor',
            field=models.CharField(default='ブラック', max_length=100),
        ),
        migrations.AddField(
            model_name='interior',
            name='seat',
            field=models.CharField(default='ファブリック･ブラック', max_length=100),
        ),
    ]
