# Generated by Django 5.2.3 on 2025-07-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_interior_interiorcolor_interior_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionpackage',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='optionpackage',
            name='listItems',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='optionpackage',
            name='subtitle',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='optionpackage',
            name='title',
            field=models.CharField(default='オプションパッケージ', max_length=100),
        ),
    ]
