# Generated by Django 5.2.3 on 2025-07-24 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_optionpackage_comment_optionpackage_listitems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numberplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numberplates', to='api.car')),
            ],
        ),
        migrations.CreateModel(
            name='TireUpgrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tire_upgrade', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(default='寒冷地仕様', max_length=100)),
                ('description', models.CharField(default='※上記オプション以外をご希望のお客様は取扱い販売店にお問合せください', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_upgrades', to='api.car')),
            ],
        ),
    ]
