# Generated by Django 5.2.3 on 2025-07-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_numberplate_tireupgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiorexteriorupgrade',
            name='imgurl',
            field=models.CharField(default='default_upgrade.png', max_length=255),
        ),
        migrations.AddField(
            model_name='interiorexteriorupgrade',
            name='is_exterior',
            field=models.BooleanField(default=False),
        ),
    ]
