# Generated by Django 5.2.3 on 2025-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_interiorexteriorupgrade_imgurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='imgurl',
            field=models.CharField(default='default_numberplate.png', max_length=100),
        ),
    ]
