# Generated by Django 5.2.3 on 2025-07-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_numberplate_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='color_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='grade_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='imgname',
            field=models.CharField(default='default.png', max_length=100),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='interior_exterior_upgrade_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='interior_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='option_package_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='option_package_listitems',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tire_upgrade_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberplate',
            name='numberplate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
