# Generated by Django 5.2.3 on 2025-07-25 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_bookmark_color_id_bookmark_grade_id_bookmark_imgname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 25, 3, 45, 48, 696334, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
