# Generated by Django 5.2.3 on 2025-07-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bookmark_created_at_bookmark_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='numberplate_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
