# Generated by Django 5.2.3 on 2025-08-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_bookmark_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_upFrontFee',
            field=models.BooleanField(default=False),
        ),
    ]
