# Generated by Django 5.2.3 on 2025-08-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_bookmark_is_upfrontfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='interior_exterior_upgrade_id',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='interior_exterior_upgrade_ids',
            field=models.JSONField(default=list),
        ),
    ]
