# Generated by Django 5.2.3 on 2025-08-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_bookmark_interior_exterior_upgrade_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='tire_upgrade_id',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tire_upgrade_ids',
            field=models.JSONField(default=list),
        ),
    ]
