# Generated by Django 5.2.3 on 2025-08-08 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_bookmark_tire_upgrade_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='carid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.car'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='numberplate_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
