# Generated by Django 5.2.3 on 2025-08-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_bookmark_carid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
